# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{

    environment.systemPackages = with pkgs; [
        alsa-utils
    ];

   systemd.services.x1-fix = {
   description = "Use alsa-utils to fix sound interference on Thinkpad x1 Nano";
   serviceConfig = {
     Type = "simple";
     ExecStart = "${pkgs.alsa-tools}/bin/hda-verb /dev/snd/hwC0D0 0x1d SET_PIN_WIDGET_CONTROL 0x0";
     Restart = "on-failure";
   };
   wantedBy = [ "default.target" ];
 };

    services = {
    # for SSD/NVME
    fstrim.enable = true;
    };
  
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")

    ];

  boot = { 
    initrd = {
      availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
      kernelModules = [ ];
      supportedFilesystems = [];
      };
    kernelModules = [ "kvm-intel"];
    extraModulePackages = [ ];
    kernelParams = [ "amd_pstate=active" ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/01ef4d7a-2939-499b-8d61-5e4fb5328495";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A60D-8E34";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
